version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    machine:
      image: android:2023.04.01
      resource_class: arm.medium
    steps:
      - run: ruby -v
      - ruby/install:
          version: '3.2.0'
      - run: ruby -v
