version: 2.1

orbs:
  ruby: circleci/ruby@2.0.0

jobs:
  build:
    docker:
      - image: cimg/android:2023.02
    steps:
      - run: ruby -v
      - ruby/install:
          version: '3.2'
      - run: ruby -v
