version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2022.09-node
    working_directory: ~/code
    steps:
      - checkout
      - run: gem install bundler --path=vendor/bundler && bundle update
